config:
  libraries:
    gcp:
      params:
        source: github.com/aroq/toolbox-gcp
        image: aroq/toolbox-gcp
      commands:
        gcloud:
          params:
            cmd: gcloud/gcloud
tools:
  gcloud:
    from: config.libraries.gcp.commands.gcloud
