config:
  libraries:
    cloud:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
      commands:
        gcp:
          params:
            cmd: cloud/gcp
            variant_config_context:
            - gcp
          cluster:
            params:
              cmd: cloud/cluster
              variant_config_context:
              - cluster
        kubectl:
          params:
            cmd: cloud/kubectl
        chamber:
          params:
            cmd: cloud/chamber
        terraform:
          params:
            cmd: cloud/terraform
  profiles:
    cloud:
      aws:
        params:
          env:
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            AWS_SESSION_TOKEN:
            AWS_SECURITY_TOKEN:
          variant_config_context:
          - aws

  environments:
    dev: &env
      cloud:
        gcp:
          clusters:
            main:
              params:
                variant_config_context:
                - main
            secondary:
              params:
                variant_config_context:
                - secondary
    prod:
      <<: *env

tools:
  gcp:
    from:
    - config.libraries.cloud.commands.gcp
    - config.profiles.cloud.aws
  cluster:
    from:
    - config.libraries.cloud.commands.gcp.cluster
    - config.profiles.cloud.aws
  chamber:
    from:
    - config.libraries.cloud.commands.chamber
  terraform/terraform:
    from: config.libraries.cloud.commands.terraform


