config:
  cloud:
    libraries:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
      commands:
        # gcloud:
          # params:
            # cmd: cloud/gcloud
        chamber:
          params:
            cmd: cloud/chamber
        terraform:
          params:
            cmd: cloud/terraform

    profiles:
      aws:
        params:
          env:
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            AWS_SESSION_TOKEN:
            AWS_SECURITY_TOKEN:
          variant_config_context:
          - aws
        chamber:
          params:
            variant_config_context:
            - aws.chamber

tools:
  gcloud/default:
    from:
    - config.cloud.libraries.commands.gcloud
    - config.cloud.profiles.aws
  chamber:
    from:
    - config.cloud.libraries.commands.chamber
    - config.profiles.aws
  terraform:
    from: config.cloud.libraries.commands.terraform

