config:
  libraries:
    cloud:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
      commands:
        gcloud:
          params:
            cmd: cloud/gcloud
        chamber:
          params:
            cmd: cloud/chamber
        terraform:
          params:
            cmd: cloud/terraform

  profiles:
    aws:
      params:
        env:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_SESSION_TOKEN:
          AWS_SECURITY_TOKEN:
        variant_config_context:
        - aws

tools:
  gcloud/gcloud:
    from:
    - config.libraries.cloud.commands.gcloud
    - config.profiles.aws
  chamber:
    from:
    - config.libraries.cloud.commands.chamber
    - config.profiles.aws
  terraform:
    from: config.libraries.cloud.commands.terraform
