config:
  libraries:
    cloud:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
      commands:
        gcloud:
          params:
            cmd: cloud/gcloud
        chamber:
          params:
            cmd: cloud/chamber
        terraform:
          params:
            cmd: cloud/terraform

  profiles:
    cloud:
      gcp:
        params:
          variant_config_context:
          - gcp
      aws:
        params:
          env:
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            AWS_SESSION_TOKEN:
            AWS_SECURITY_TOKEN:
          variant_config_context:
          - aws
        chamber:
          params:
            variant_config_context:
            - aws.chamber

tools:
  gcloud/default:
    from:
    - config.libraries.cloud.commands.gcloud
    - config.profiles.cloud.gcp
    - config.profiles.cloud.aws
  chamber:
    from:
    - config.libraries.cloud.commands.chamber
    - config.profiles.cloud.gcp
    - config.profiles.aws
  terraform:
    from: config.libraries.cloud.commands.terraform


