config:
  libraries:
    cloud:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
      commands:
        gcloud:
          params:
            cmd: cloud/gcloud
tools:
  gcloud:
    from: config.libraries.cloud.commands.gcloud
