config:
  libraries:
    cloud:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
      commands:
        gcp:
          params:
            cmd: cloud/gcp
        kubectl:
          params:
            cmd: cloud/kubectl
        chamber:
          params:
            cmd: cloud/chamber
        terraform:
          params:
            cmd: cloud/terraform

  environments:
    dev: &env
      cloud:
        gcp:
          params:
            variant_config_context:
            - gcp
          clusters:
            main:
              params:
                variant_config_context:
                - main
            secondary:
              params:
                variant_config_context:
                - secondary
        aws:
          params:
            env:
              AWS_ACCESS_KEY_ID:
              AWS_SECRET_ACCESS_KEY:
              AWS_SESSION_TOKEN:
              AWS_SECURITY_TOKEN:
            variant_config_context:
            - aws
          chamber:
            params:
              variant_config_context:
              - aws.chamber
    prod:
      <<: *env

tools:
  gcp/gcp:
    from:
    - config.libraries.cloud.commands.gcp
  chamber:
    from:
    - config.libraries.cloud.commands.chamber
  terraform/terraform:
    from: config.libraries.cloud.commands.terraform


