config:
  libraries:
    params:
      tool_dirs:
      - toolbox/.toolbox/deps/toolbox-cloud
    cloud:
      params:
        destination: cloud
        source: github.com/aroq/toolbox-cloud
        image: aroq/toolbox-cloud
        config_context_prefix:
        - cloud
      commands:
        gcp:
          params:
            cmd: cloud/gcp
            config_context_prefix:
            - gcp
          cluster:
            params:
              cmd: cloud/cluster
              config_context_prefix:
              - cluster
            aws:
              gpg:
                params:
                  cmd: cluster_gcp_aws_gpg
          kubectl:
            params:
              cmd: cloud/kubectl
        chamber:
          params:
            cmd: cloud/chamber
        terraform:
          params:
            cmd: cloud/terraform
  profiles:
    cloud:
      aws:
        params:
          env:
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            AWS_SESSION_TOKEN:
            AWS_SECURITY_TOKEN:
          config_context_prefix:
          - aws

  environments:
    dev: &env
      cloud:
        gcp:
          clusters:
            main:
              params:
                config_context_prefix:
                - main
            secondary:
              params:
                config_context_prefix:
                - secondary
    prod:
      <<: *env

tools:
  gcp:
    from:
    - config.libraries.cloud.commands.gcp
    - config.profiles.cloud.aws
  kubectl:
    from:
    - config.libraries.cloud.commands.gcp.kubectl
    - config.profiles.cloud.aws
  chamber:
    from:
    - config.libraries.cloud.commands.chamber
  terraform/terraform:
    from: config.libraries.cloud.commands.terraform
